/**
 * Copyright (C) 2012 SINTEF <franck.fleurey@sintef.no>
 *
 * Licensed under the GNU LESSER GENERAL PUBLIC LICENSE, Version 3, 29 June 2007;
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * 	http://www.gnu.org/licenses/lgpl-3.0.txt
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.thingml.eTriage.desktop;

import java.awt.Color;
import org.thingml.etriage.driver.EtriageListener;
import org.thingml.etriage.driver.Etriage;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import org.thingml.bglib.BGAPITransport;
import org.thingml.bglib.BGAPI;
import org.thingml.rtcharts.swing.DataBuffer;
import org.thingml.rtcharts.swing.GraphBuffer;
//import org.thingml.rtsync.ui.TimeSyncFrame;

/**
 *
 * @author ffl
 */
public class EtriageFrame extends javax.swing.JFrame implements EtriageListener {

    private SimpleDateFormat timestampFormat = new SimpleDateFormat("HH:mm:ss.SSS");
    private DecimalFormat numFormat = new DecimalFormat("0.00");
    private DecimalFormat imunumFormat = new DecimalFormat("0.00000");
    protected BLEExplorerDialog bledialog = new BLEExplorerDialog();
    protected BitRateCounter bitrate;
    
    protected Etriage etb;
    
    /**
     * Creates new form EtriageFrame
     */
    public EtriageFrame() {
        initComponents();
        reset();
        bledialog.setModal(true);
    }
    
    boolean hideMode = false;
    
    public void disableConnectionButton() {
        jButtonConnection.setEnabled(false);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        hideMode = true;
    }
    
    protected void reset() {
        if (etb != null) { 
            etb.removeEtbListener(this);
            etb.disconnect();
        }
        jProgressBarValueTemp.setValue(0);
        jTextFieldIntervalTemp.setText("N/A");
        jProgressBarValueTemp.setString("N/A");
        jCheckBoxSubscribeTemp.setSelected(false);
        
        
        jProgressBarBatt.setValue(0);
        jProgressBarBatt.setString("N/A");
        jCheckBoxSubscribeBatt.setSelected(true);
        
        jTextFieldInfoFW.setText("N/A");
        jTextFieldInfoHW.setText("N/A");
        jTextFieldInfoSerial.setText("N/A");
        jTextFieldInfoModel.setText("N/A");
        jTextFieldInfoManuf.setText("N/A");
        
        last_ski = -1;
        last_hum = -1;
        last_mag = -1;
        last_imu = -1;
        last_qat = -1;
        
         if (logform != null) {
            logform.setVisible(false);
            logform.dispose();
         }
    } 
    
    public void setSensor(Etriage sensor) {
        reset();
        etb = sensor;
        etb.addEtbListener(this);
        
        if (bitrate != null) bitrate.request_stop();
        bitrate = new BitRateCounter();
        bitrate.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButtonConnection = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButtonLog = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTextFieldInfoManuf = new javax.swing.JTextField();
        jTextFieldInfoModel = new javax.swing.JTextField();
        jTextFieldInfoHW = new javax.swing.JTextField();
        jTextFieldInfoFW = new javax.swing.JTextField();
        jTextFieldInfoSerial = new javax.swing.JTextField();
        jButtonReqInfo = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        jCheckBoxSubscribeTemp = new javax.swing.JCheckBox();
        jCheckBoxSubscribeBatt = new javax.swing.JCheckBox();
        jCheckBoxBWTest = new javax.swing.JCheckBox();
        jPanel19 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldIntervalTemp = new javax.swing.JTextField();
        jButtonReadIntervalTemp = new javax.swing.JButton();
        jButtonWriteIntervalTemp = new javax.swing.JButton();
        jButtonWriteEtbLocation = new javax.swing.JButton();
        jButtonReadEtbLocation = new javax.swing.JButton();
        jTextFieldEtbLocation = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldEtbDateTime = new javax.swing.JTextField();
        jButtonReadEtbDateTime = new javax.swing.JButton();
        jButtonWriteEtbDateTime = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldEtbPosition = new javax.swing.JTextField();
        jButtonReadEtbPosition = new javax.swing.JButton();
        jButtonWriteEtbPositon = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldEtbTriageLevel = new javax.swing.JTextField();
        jButtonReadEtbTriageLevel = new javax.swing.JButton();
        jButtonWriteEtbTriageLevel = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldEtbLocationID = new javax.swing.JTextField();
        jButtonReadLocationID = new javax.swing.JButton();
        jButtonWriteLocationID = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldConnectionInterval = new javax.swing.JTextField();
        jButtonReadConnetionInterval = new javax.swing.JButton();
        jButtonWriteConnectionInterval = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jProgressBarValueTemp = new javax.swing.JProgressBar();
        jButtonGraphTemp = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jProgressBarBatt = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("eTriage");
        setBackground(new java.awt.Color(204, 204, 204));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Connection"));

        jButtonConnection.setText("Connection...");
        jButtonConnection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConnectionActionPerformed(evt);
            }
        });

        jButton1.setText("Bandwidth...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonLog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file-3.png"))); // NOI18N
        jButtonLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonConnection)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLog)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonConnection)
                        .addComponent(jButton1))
                    .addComponent(jButtonLog, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder("Device Informations"));

        jLabel23.setText("Manufacturer:");

        jLabel24.setText("Model:");

        jLabel25.setText("Hardware revision:");

        jLabel26.setText("Firmware revision:");

        jLabel27.setText("Serial Number:");

        jTextFieldInfoManuf.setEditable(false);
        jTextFieldInfoManuf.setText("N/A");
        jTextFieldInfoManuf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldInfoManufActionPerformed(evt);
            }
        });

        jTextFieldInfoModel.setEditable(false);
        jTextFieldInfoModel.setText("N/A");

        jTextFieldInfoHW.setEditable(false);
        jTextFieldInfoHW.setText("N/A");

        jTextFieldInfoFW.setEditable(false);
        jTextFieldInfoFW.setText("N/A");
        jTextFieldInfoFW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldInfoFWActionPerformed(evt);
            }
        });

        jTextFieldInfoSerial.setEditable(false);
        jTextFieldInfoSerial.setText("N/A");

        jButtonReqInfo.setText("Get Infos");
        jButtonReqInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReqInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jButtonReqInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel17Layout.createSequentialGroup()
                                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel26))
                                .addGap(7, 7, 7)
                                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldInfoFW)
                                    .addComponent(jTextFieldInfoSerial)))
                            .addGroup(jPanel17Layout.createSequentialGroup()
                                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel23))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldInfoModel)
                                    .addComponent(jTextFieldInfoManuf)
                                    .addComponent(jTextFieldInfoHW))))
                        .addGap(2, 2, 2))))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jTextFieldInfoManuf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jTextFieldInfoModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jTextFieldInfoHW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldInfoFW))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldInfoSerial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonReqInfo)
                .addContainerGap())
        );

        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder("Subscriptions"));

        jCheckBoxSubscribeTemp.setText("Subscribe Temperature");
        jCheckBoxSubscribeTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSubscribeTempActionPerformed(evt);
            }
        });

        jCheckBoxSubscribeBatt.setText("Subscribe Battery");
        jCheckBoxSubscribeBatt.setOpaque(false);
        jCheckBoxSubscribeBatt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSubscribeBattActionPerformed(evt);
            }
        });

        jCheckBoxBWTest.setText("Subscribe Test Pattern");
        jCheckBoxBWTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxBWTestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxSubscribeTemp)
                    .addComponent(jCheckBoxSubscribeBatt)
                    .addComponent(jCheckBoxBWTest))
                .addGap(0, 8, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addComponent(jCheckBoxSubscribeTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxSubscribeBatt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxBWTest)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel19.setBorder(javax.swing.BorderFactory.createTitledBorder("Parameters"));

        jLabel3.setText("Temperature interval:");

        jTextFieldIntervalTemp.setText("0");
        jTextFieldIntervalTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIntervalTempActionPerformed(evt);
            }
        });

        jButtonReadIntervalTemp.setText("Read");
        jButtonReadIntervalTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReadIntervalTempActionPerformed(evt);
            }
        });

        jButtonWriteIntervalTemp.setText("Write");
        jButtonWriteIntervalTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWriteIntervalTempActionPerformed(evt);
            }
        });

        jButtonWriteEtbLocation.setText("Write");
        jButtonWriteEtbLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWriteEtbLocationActionPerformed(evt);
            }
        });

        jButtonReadEtbLocation.setText("Read");
        jButtonReadEtbLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReadEtbLocationActionPerformed(evt);
            }
        });

        jTextFieldEtbLocation.setText("0");
        jTextFieldEtbLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEtbLocationActionPerformed(evt);
            }
        });

        jLabel4.setText("etb Location");

        jLabel5.setText("etb Date Time");

        jTextFieldEtbDateTime.setText("0");
        jTextFieldEtbDateTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEtbDateTimeActionPerformed(evt);
            }
        });

        jButtonReadEtbDateTime.setText("Read");
        jButtonReadEtbDateTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReadEtbDateTimeActionPerformed(evt);
            }
        });

        jButtonWriteEtbDateTime.setText("Write");
        jButtonWriteEtbDateTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWriteEtbDateTimeActionPerformed(evt);
            }
        });

        jLabel6.setText("etb Position");

        jTextFieldEtbPosition.setText("0");
        jTextFieldEtbPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEtbPositionActionPerformed(evt);
            }
        });

        jButtonReadEtbPosition.setText("Read");
        jButtonReadEtbPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReadEtbPositionActionPerformed(evt);
            }
        });

        jButtonWriteEtbPositon.setText("Write");
        jButtonWriteEtbPositon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWriteEtbPositonActionPerformed(evt);
            }
        });

        jLabel7.setText("etb Triage level");

        jTextFieldEtbTriageLevel.setText("0");
        jTextFieldEtbTriageLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEtbTriageLevelActionPerformed(evt);
            }
        });

        jButtonReadEtbTriageLevel.setText("Read");
        jButtonReadEtbTriageLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReadEtbTriageLevelActionPerformed(evt);
            }
        });

        jButtonWriteEtbTriageLevel.setText("Write");
        jButtonWriteEtbTriageLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWriteEtbTriageLevelActionPerformed(evt);
            }
        });

        jLabel8.setText("etb Loation ID");

        jTextFieldEtbLocationID.setText("0");
        jTextFieldEtbLocationID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEtbLocationIDActionPerformed(evt);
            }
        });

        jButtonReadLocationID.setText("Read");
        jButtonReadLocationID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReadLocationIDActionPerformed(evt);
            }
        });

        jButtonWriteLocationID.setText("Write");
        jButtonWriteLocationID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWriteLocationIDActionPerformed(evt);
            }
        });

        jLabel9.setText("Connection Interval");

        jTextFieldConnectionInterval.setText("0");
        jTextFieldConnectionInterval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldConnectionIntervalActionPerformed(evt);
            }
        });

        jButtonReadConnetionInterval.setText("Read");
        jButtonReadConnetionInterval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReadConnetionIntervalActionPerformed(evt);
            }
        });

        jButtonWriteConnectionInterval.setText("Write");
        jButtonWriteConnectionInterval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWriteConnectionIntervalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonReadEtbPosition)
                            .addComponent(jButtonReadEtbDateTime))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonWriteEtbPositon)
                            .addComponent(jButtonWriteEtbDateTime)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldEtbLocation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonReadEtbLocation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonWriteEtbLocation))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldEtbTriageLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonReadEtbTriageLevel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonWriteEtbTriageLevel))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldEtbLocationID, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonReadLocationID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonWriteLocationID))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldConnectionInterval, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonReadConnetionInterval)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonWriteConnectionInterval))))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel19Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldEtbPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel19Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel19Layout.createSequentialGroup()
                                        .addComponent(jTextFieldIntervalTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonReadIntervalTemp)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonWriteIntervalTemp))
                                    .addComponent(jTextFieldEtbDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonReadIntervalTemp)
                        .addComponent(jButtonWriteIntervalTemp))
                    .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldIntervalTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldEtbDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonReadEtbDateTime)
                    .addComponent(jButtonWriteEtbDateTime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldEtbPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonReadEtbPosition)
                    .addComponent(jButtonWriteEtbPositon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonWriteEtbTriageLevel)
                    .addComponent(jButtonReadEtbTriageLevel)
                    .addComponent(jTextFieldEtbTriageLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonWriteEtbLocation)
                    .addComponent(jButtonReadEtbLocation)
                    .addComponent(jTextFieldEtbLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldEtbLocationID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonReadLocationID)
                    .addComponent(jButtonWriteLocationID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldConnectionInterval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonReadConnetionInterval)
                    .addComponent(jButtonWriteConnectionInterval))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Skin Temperature"));

        jProgressBarValueTemp.setForeground(new java.awt.Color(255, 51, 51));
        jProgressBarValueTemp.setMaximum(45);
        jProgressBarValueTemp.setMinimum(15);
        jProgressBarValueTemp.setValue(37);
        jProgressBarValueTemp.setString("37.00°C");
        jProgressBarValueTemp.setStringPainted(true);

        jButtonGraphTemp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chart-1.png"))); // NOI18N
        jButtonGraphTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGraphTempActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jProgressBarValueTemp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonGraphTemp))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jProgressBarValueTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButtonGraphTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 20, Short.MAX_VALUE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Battery"));

        jProgressBarBatt.setForeground(new java.awt.Color(102, 102, 102));
        jProgressBarBatt.setValue(70);
        jProgressBarBatt.setStringPainted(true);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jProgressBarBatt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jProgressBarBatt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConnectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConnectionActionPerformed

        reset();
        //if (etb != null) etb.stopTimeSync();
        
        bledialog.setVisible(true);
        
        if (bledialog.isConnected()) {
            
            etb = new Etriage(bledialog.getBgapi(), bledialog.getConnection());
            etb.addEtbListener(this);
            etb.subscribeBattery();
            
            if (bitrate != null) bitrate.request_stop();
            bitrate = new BitRateCounter();
            bitrate.start();
            //jTextFieldStatus.setText("Connected.");
            
            
            etb.requestDeviceInfo();
            
        }
        if(!bledialog.isConnected()) {

            //jTextFieldStatus.setText("Not Connected.");
        }
    }//GEN-LAST:event_jButtonConnectionActionPerformed

    private void jCheckBoxSubscribeTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSubscribeTempActionPerformed
        if (etb != null) {
            if (jCheckBoxSubscribeTemp.isSelected()) {
                etb.subscribeSkinTemperature();
                etb.readSkinTemperatureInterval();
            }
            else {
                etb.unsubscribeSkinTemperature();
            }
        }
    }//GEN-LAST:event_jCheckBoxSubscribeTempActionPerformed

    private void jCheckBoxSubscribeBattActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSubscribeBattActionPerformed
        if (etb != null) {
            if (jCheckBoxSubscribeBatt.isSelected()) {
                etb.subscribeBattery();
            }
            else {
                etb.unsubscribeBattery();
            }
        }
    }//GEN-LAST:event_jCheckBoxSubscribeBattActionPerformed

    private void jTextFieldInfoManufActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldInfoManufActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldInfoManufActionPerformed

    private void jButtonReqInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReqInfoActionPerformed
        if (etb != null) etb.requestDeviceInfo();
    }//GEN-LAST:event_jButtonReqInfoActionPerformed

    private void jButtonGraphTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGraphTempActionPerformed
    SkinTempGraphFrame tempform = new SkinTempGraphFrame(buff_skinTemperature);
    tempform.setSize(600, 300);
    tempform.setVisible(true);
    }//GEN-LAST:event_jButtonGraphTempActionPerformed

    
    FileLoggerForm logform;
            
    private void jButtonLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogActionPerformed
        if (logform != null) {
            logform.setVisible(false);
            logform.dispose();
        }
        if (etb != null) {
            logform = new FileLoggerForm(etb);
            logform.pack();
            logform.setVisible(true);
        }
        else {
            System.err.println("Not Connected.");
        }
    }//GEN-LAST:event_jButtonLogActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
       
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (hideMode) return;
        System.out.println("Closing connections.");
        if (etb!=null) etb.disconnect();
        if (bledialog!=null) bledialog.disconnect();
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    private int ping_seq = 0;
    
    private void jCheckBoxBWTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxBWTestActionPerformed
        if (etb != null) {
            if (jCheckBoxBWTest.isSelected()) etb.subscribeTestPattern();
            else etb.unsubscribeTestPattern();
        }
    }//GEN-LAST:event_jCheckBoxBWTestActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        BitRateGraphFrame tempform = new BitRateGraphFrame(brate);
        tempform.setSize(600, 200);
        tempform.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    private void jTextFieldInfoFWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldInfoFWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldInfoFWActionPerformed

    private void jButtonWriteEtbDateTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWriteEtbDateTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonWriteEtbDateTimeActionPerformed

    private void jButtonReadEtbDateTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReadEtbDateTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonReadEtbDateTimeActionPerformed

    private void jTextFieldEtbDateTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEtbDateTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEtbDateTimeActionPerformed

    private void jTextFieldEtbLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEtbLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEtbLocationActionPerformed

    private void jButtonReadEtbLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReadEtbLocationActionPerformed
        if (etb != null) etb.readetbLocation();
    }//GEN-LAST:event_jButtonReadEtbLocationActionPerformed

    private void jButtonWriteEtbLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWriteEtbLocationActionPerformed
        if (etb != null) etb.setetbLocation(Integer.parseInt(jTextFieldEtbLocation.getText()));
    }//GEN-LAST:event_jButtonWriteEtbLocationActionPerformed

    private void jButtonWriteIntervalTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWriteIntervalTempActionPerformed
        if (etb != null) etb.setSkinTemperatureInterval(Integer.parseInt(jTextFieldIntervalTemp.getText()));
    }//GEN-LAST:event_jButtonWriteIntervalTempActionPerformed

    private void jButtonReadIntervalTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReadIntervalTempActionPerformed
        if (etb != null) etb.readSkinTemperatureInterval();
    }//GEN-LAST:event_jButtonReadIntervalTempActionPerformed

    private void jTextFieldIntervalTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIntervalTempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIntervalTempActionPerformed

    private void jTextFieldEtbPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEtbPositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEtbPositionActionPerformed

    private void jButtonReadEtbPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReadEtbPositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonReadEtbPositionActionPerformed

    private void jButtonWriteEtbPositonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWriteEtbPositonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonWriteEtbPositonActionPerformed

    private void jTextFieldEtbTriageLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEtbTriageLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEtbTriageLevelActionPerformed

    private void jButtonReadEtbTriageLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReadEtbTriageLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonReadEtbTriageLevelActionPerformed

    private void jButtonWriteEtbTriageLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWriteEtbTriageLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonWriteEtbTriageLevelActionPerformed

    private void jTextFieldEtbLocationIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEtbLocationIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEtbLocationIDActionPerformed

    private void jButtonReadLocationIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReadLocationIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonReadLocationIDActionPerformed

    private void jButtonWriteLocationIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWriteLocationIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonWriteLocationIDActionPerformed

    private void jTextFieldConnectionIntervalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldConnectionIntervalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldConnectionIntervalActionPerformed

    private void jButtonReadConnetionIntervalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReadConnetionIntervalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonReadConnetionIntervalActionPerformed

    private void jButtonWriteConnectionIntervalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWriteConnectionIntervalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonWriteConnectionIntervalActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {
            // Set System L&F 
            UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
            System.out.println(UIManager.getCrossPlatformLookAndFeelClassName());
        } catch (Exception e) {
            e.printStackTrace();
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EtriageFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonConnection;
    private javax.swing.JButton jButtonGraphTemp;
    private javax.swing.JButton jButtonLog;
    private javax.swing.JButton jButtonReadConnetionInterval;
    private javax.swing.JButton jButtonReadEtbDateTime;
    private javax.swing.JButton jButtonReadEtbLocation;
    private javax.swing.JButton jButtonReadEtbPosition;
    private javax.swing.JButton jButtonReadEtbTriageLevel;
    private javax.swing.JButton jButtonReadIntervalTemp;
    private javax.swing.JButton jButtonReadLocationID;
    private javax.swing.JButton jButtonReqInfo;
    private javax.swing.JButton jButtonWriteConnectionInterval;
    private javax.swing.JButton jButtonWriteEtbDateTime;
    private javax.swing.JButton jButtonWriteEtbLocation;
    private javax.swing.JButton jButtonWriteEtbPositon;
    private javax.swing.JButton jButtonWriteEtbTriageLevel;
    private javax.swing.JButton jButtonWriteIntervalTemp;
    private javax.swing.JButton jButtonWriteLocationID;
    private javax.swing.JCheckBox jCheckBoxBWTest;
    private javax.swing.JCheckBox jCheckBoxSubscribeBatt;
    private javax.swing.JCheckBox jCheckBoxSubscribeTemp;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JProgressBar jProgressBarBatt;
    private javax.swing.JProgressBar jProgressBarValueTemp;
    private javax.swing.JTextField jTextFieldConnectionInterval;
    private javax.swing.JTextField jTextFieldEtbDateTime;
    private javax.swing.JTextField jTextFieldEtbLocation;
    private javax.swing.JTextField jTextFieldEtbLocationID;
    private javax.swing.JTextField jTextFieldEtbPosition;
    private javax.swing.JTextField jTextFieldEtbTriageLevel;
    private javax.swing.JTextField jTextFieldInfoFW;
    private javax.swing.JTextField jTextFieldInfoHW;
    private javax.swing.JTextField jTextFieldInfoManuf;
    private javax.swing.JTextField jTextFieldInfoModel;
    private javax.swing.JTextField jTextFieldInfoSerial;
    private javax.swing.JTextField jTextFieldIntervalTemp;
    // End of variables declaration//GEN-END:variables

    protected GraphBuffer buff_skinTemperature = new GraphBuffer(100);
    
    protected GraphBuffer buff_t1 = new GraphBuffer(100);
    protected GraphBuffer buff_h1 = new GraphBuffer(100);
    protected GraphBuffer buff_t2 = new GraphBuffer(100);
    protected GraphBuffer buff_h2 = new GraphBuffer(100);
    
    protected GraphBuffer buff_ax = new GraphBuffer(250);
    protected GraphBuffer buff_ay = new GraphBuffer(250);
    protected GraphBuffer buff_az = new GraphBuffer(250);
    
    protected GraphBuffer buff_gx = new GraphBuffer(250);
    protected GraphBuffer buff_gy = new GraphBuffer(250);
    protected GraphBuffer buff_gz = new GraphBuffer(250);
    
    protected GraphBuffer buff_mx = new GraphBuffer(150);
    protected GraphBuffer buff_my = new GraphBuffer(150);
    protected GraphBuffer buff_mz = new GraphBuffer(150);
    
    protected GraphBuffer buff_qw = new GraphBuffer(250);
    protected GraphBuffer buff_qx = new GraphBuffer(250);
    protected GraphBuffer buff_qy = new GraphBuffer(250);
    protected GraphBuffer buff_qz = new GraphBuffer(250);
    
    protected GraphBuffer buff_dski = new GraphBuffer(100);
    protected GraphBuffer buff_dhum = new GraphBuffer(100);
    protected GraphBuffer buff_dmag = new GraphBuffer(100);
    protected GraphBuffer buff_dimu = new GraphBuffer(100);
    protected GraphBuffer buff_dqat = new GraphBuffer(100);
    protected GraphBuffer buff_test = new GraphBuffer(100);
    
    long last_ski = -1;
    long last_hum = -1;
    long last_mag = -1;
    long last_imu = -1;
    long last_qat = -1;
    long last_test = -1;
    

    public void battery(int battery, int timestamp) {
        jProgressBarBatt.setValue(battery);
        jProgressBarBatt.setString(battery + "%");
    }


    @Override
    public void manufacturer(String value) {
        jTextFieldInfoManuf.setText(value);
    }

    @Override
    public void model_number(String value) {
        jTextFieldInfoModel.setText(value);
    }

    @Override
    public void serial_number(String value) {
        jTextFieldInfoSerial.setText(value);
        setTitle("eTriage [" + value + "]");
    }

    @Override
    public void hw_revision(String value) {
        jTextFieldInfoHW.setText(value);
    }

    @Override
    public void fw_revision(String value) {
        jTextFieldInfoFW.setText(value);
    }

    @Override
    public void humidityInterval(int value) {
    }

    public void imuInterval(int value) {
    }

    @Override
    public void magnetometer(int x, int y, int z, int timestamp) {
    }

    @Override
    public void magnetometerInterval(int value) {
    }

    @Override
    public void humidity(int t1, int h1, int t2, int h2, int timestamp) {
    }

    @Override
    public void imu(int ax, int ay, int az, int gx, int gy, int gz, int timestamp) {
    }
    
    
    @Override
    public void quaternion(int iw, int ix, int iy, int iz, int timestamp) {
    }

    @Override
    public void imuMode(int value) {
    }
    
    @Override
    public void imuInterrupt(int value) {
    }

    @Override
    public void testPattern(byte[] data, int timestamp) {
        long time = timestamp;
        int diff = (int)(time - last_test);
        if (diff < 0) diff += 0x100;
        if (last_test > 0) {
           buff_test.insertData( diff ); 
        }
        last_test = time;
    }

    @Override
    public void timeSync(int seq, int timestamp) {
    }

    protected GraphBuffer brate = new GraphBuffer(100);

    @Override
    public void alertLevel(int value) {
//        jComboBox2.setSelectedIndex(value);
    }
    
    
    public void skinTemperature(double temp, int timestamp) {
        jProgressBarValueTemp.setString(numFormat.format(temp) + "°C");
        jProgressBarValueTemp.setValue((int)temp);
        //jTextFieldTimeTemp.setText(""+timestamp);
        buff_skinTemperature.insertData((int)(temp*100));
        
        long time = timestamp;
        int diff = (int)(time - last_ski);
        if (diff < 0) diff += 0x40000;
        if (last_ski > 0) {
           buff_dski.insertData( diff ); 
        }
        last_ski = time;
        
    }

    public void skinTemperatureInterval(int value) {
        jTextFieldIntervalTemp.setText("" + value);
    }

    public void etbLocation(int value) {
        jTextFieldEtbLocation.setText("" + value);
    }
    class BitRateCounter extends Thread {
    
        private int update_rate = 100; // 1000 ms

        private boolean stop = false;
        public void request_stop() {
            stop = true;
        }

        public void run() {

           long old_time = System.currentTimeMillis();
           long old_bytes = etb.getReceivedBytes();

           while (etb != null && !stop) {
                try {
                    Thread.sleep(update_rate);
                } catch (InterruptedException ex) {
                    Logger.getLogger(BitRateCounter.class.getName()).log(Level.SEVERE, null, ex);
                }
                long new_time = System.currentTimeMillis();
                long new_bytes = etb.getReceivedBytes();

                int bitrate = (int)(((new_bytes - old_bytes) * 1000) / (new_time - old_time));

                brate.insertData(bitrate);
                
                old_time = new_time;
                old_bytes = new_bytes;
           }
        }
    }
}
